import os

lessons = [
    {"file":"tawheed-1-1","unit":1,"num":1,"ten":"The Three Principles","tar":"الأصول الثلاثة","cen":"Allah is my Lord, Islam is my religion, and Muhammad (\ufe9f) is my Prophet.","car":"الله ربي، الإسلام ديني، ومحمد (\ufe9f) نبيّ.","ben":"<p>Every Muslim should know three important things:</p>\n<h3>1. Allah is my Lord</h3>\n<p>Allah is the One who created me and everything in the universe. He is my Lord and the Lord of all creation.</p>\n<h3>2. Islam is my religion</h3>\n<p>Islam is the religion that Allah chose for us. It guides us to do good and stay away from wrong.</p>\n<h3>3. Muhammad (\ufe9f) is my Prophet</h3>\n<p>Prophet Muhammad (\ufe9f) is the last and greatest of all prophets. He taught us how to worship Allah and be good people.</p>\n<div class='lesson-highlight'>Remember these three principles and you will be on the Straight Path!</div>","bar":"<p>كل مسلم يجب أن يعرف ثلاثة أشياء مهمة:</p>\n<h3>١. الله ربي</h3>\n<p>الله هو الذي خلقني وخلق كل شيء في الكون. هو ربي ورب جميع الخليقة.</p>\n<h3>٢. الإسلام ديني</h3>\n<p>الإسلام هو الدين الذي اختاره الله لنا. يهدينا إلى فعل الخير واجتناب الشر.</p>\n<h3>٣. محمّد نبيّي</h3>\n<p>النبي محمّد (\ufe9f) هو آخر جميع الأنبياء وأعظمهم. علّمنا كيف نعبد الله ونكون أشخاصاً طيبين.</p>\n<div class='lesson-highlight'>تذكر هذه المبادئ الثلاثة وستكون على الطريق المستقيم!</div>","prev":None,"next":"tawheed-1-2"},
    {"file":"tawheed-1-2","unit":1,"num":2,"ten":"Allah the Creator","tar":"الله الخالق","cen":"Allah created me, all people, animals, birds, the sun, the moon, and everything.","car":"الله خلقني وخلق جميع الناس والحيوانات والطير والشمس والقمر وكل شيء.","ben":"<p>Allah is the Creator of everything! Look around you &#8212; everything you see was created by Allah.</p>\n<h3>Allah Created People</h3>\n<p>Every person in the world was created by Allah. He created you and me!</p>\n<h3>Allah Created Animals</h3>\n<p>All the animals &#8212; cats, dogs, birds, fish &#8214; were all created by Allah. Every creature is special.</p>\n<h3>Allah Created the Sun and Moon</h3>\n<p>The sun gives us light during the day. The moon shines at night. Allah created them both!</p>\n<div class='lesson-highlight'>When you see a beautiful flower or a big mountain, remember &#8212; Allah created it all!</div>","bar":"<p>الله خالق كل شيء! انظر حولك &#8212; كل ما تراه خلقه الله.</p>\n<h3>الله خلق الناس</h3>\n<p>كل إنسان في العالم خلقه الله. خلقك وخلقني!</p>\n<h3>الله خلق الحيوانات</h3>\n<p>جميع الحيوانات &#8212; القطط والكلاب والطيور والأسماك &#8212; خلقها الله. كل مخلوق مميز.</p>\n<h3>الله خلق الشمس والقمر</h3>\n<p>الشمس ت给予نا الضوء في النهار. القمر يضيء في الليل. خلقهما الله!</p>\n<div class='lesson-highlight'>عندما ترى زهرة جميلة أو جبلاً كبيراً، تذكّر &#8212; الله خلقها كلها!</div>","prev":"tawheed-1-1","next":"tawheed-1-3"},
    {"file":"tawheed-1-3","unit":1,"num":3,"ten":"Allah My Creator","tar":"الله خالقي","cen":"Allah is the One who created me, including my hearing and my sight.","car":"الله هو الذي خلقني بما في ذلك سمعي وبصري.","ben":"<p>Allah created you in a special and wonderful way!</p>\n<h3>Allah Created Your Body</h3>\n<p>He gave you two eyes to see, two ears to hear, a mouth to speak, and hands to play!</p>\n<h3>Allah Created Your Senses</h3>\n<p>Can you hear the birds singing? That is because Allah gave you hearing. Can you see the colors around you? That is because Allah gave you sight.</p>\n<h3>Be Grateful to Allah</h3>\n<p>We should always say <strong>Alhamdulillah</strong> (\u0627\u0644\u062d\u0645\u062f \u0644\u0644\u0647) for everything He gave us.</p>\n<div class='lesson-highlight'>Allah created you perfectly. Say: Alhamdulillah!</div>","bar":"<p>الله خلقك بطريقة مميزة ورائعة!</p>\n<h3>الله خلق جسدك</h3>\n<p>أعطاك عينين للبصر، وأذنين للسمع، وفماً للكلام، ويدين للعب!</p>\n<h3>الله خلق حواسك</h3>\n<p>هل تسمع العصافير تغني؟ هذا لأن الله أعطاك السمع. هل ترى الألوان من حولك؟ هذا لأن الله أعطاك البصر.</p>\n<h3>كن شكوراً لله</h3>\n<p>يجب أن نقول دائماً الحمد لله على كل ما أعطانا الله.</p>\n<div class='lesson-highlight'>الله خلقك بشكل مثالي. قل: الحمد لله!</div>","prev":"tawheed-1-2","next":"tawheed-1-4"},
    {"file":"tawheed-1-4","unit":1,"num":4,"ten":"Allah the Owner","tar":"الله المالك","cen":"Allah is the Owner of the heavens, the earth, and everything in existence.","car":"الله مالك السماوات والأرض وكل ما فيه.","ben":"<p>Allah owns everything in the universe!</p>\n<h3>Allah Owns the Heavens</h3>\n<p>The sky, the stars, the planets &#8212; they all belong to Allah. No one else owns them.</p>\n<h3>Allah Owns the Earth</h3>\n<p>The mountains, the rivers, the trees, and the oceans &#8212; everything on earth belongs to Allah.</p>\n<h3>Allah Owns You and Me</h3>\n<p>We all belong to Allah. He created us, and we will return to Him.</p>\n<div class='lesson-highlight'>Everything is owned by Allah. We are His servants!</div>","bar":"<p>الله يملك كل شيء في الكون!</p>\n<h3>الله يملك السماوات</h3>\n<p>السماء والنجوم والكواكب &#8212; كلها ملك لله.</p>\n<h3>الله يملك الأرض</h3>\n<p>الجبال والأنهار والأشجار والمحيطات &#8212; كل شيء على الأرض ملك لله.</p>\n<h3>الله يملكك و يملكني</h3>\n<p>نحن جميعاً ملك لله. خلقنا وإليه نرجع.</p>\n<div class='lesson-highlight'>كل شيء ملك لله. نحن عباده!</div>","prev":"tawheed-1-3","next":"tawheed-1-5"},
    {"file":"tawheed-1-5","unit":1,"num":5,"ten":"Allah the Provider","tar":"الله الرزاق","cen":"There is no provider except Allah. He provides us with food, drink, and sustains all creatures.","car":"لا رزاق إلا الله. يرزقنا بالطعام والشراب ويُرزق جميع المخلوقات.","ben":"<p>Allah provides for everyone and everything!</p>\n<h3>Allah Provides Food</h3>\n<p>Every time you eat a meal, remember &#8212; Allah sent that food to you. The fruits, the bread, the milk &#8212; all from Allah.</p>\n<h3>Allah Provides Water</h3>\n<p>Fresh, clean water comes from Allah. The rain falls by His command.</p>\n<h3>Allah Provides for All Creatures</h3>\n<p>Even the smallest ant and the biggest whale &#8212; Allah provides food for all of them.</p>\n<div class='lesson-highlight'>When you sit down to eat, say: Bismillah! Allah is the Provider.</div>","bar":"<p>الله يرزق الجميع وكل شيء!</p>\n<h3>الله يرزقنا الطعام</h3>\n<p>في كل مرة تأكل فيها وجبة، تذكّر &#8212; الله أرسل لك ذلك الطعام.</p>\n<h3>الله يرزقنا الماء</h3>\n<p>الماء العذب النظيف من الله. المطر ينزل بأمره.</p>\n<h3>الله يرزق جميع المخلوقات</h3>\n<p>حتى النملة الصغيرة والحوت الكبير &#8212; الله يرزقها جميعاً.</p>\n<div class='lesson-highlight'>عندما تجلس للأكل، قل: بسم الله! الله هو الرزّاق.</div>","prev":"tawheed-1-4","next":"tawheed-2-1"},
    {"file":"tawheed-2-1","unit":2,"num":1,"ten":"Why Did Allah Create Us?","tar":"لماذا خلقنا الله؟","cen":"Allah created us solely to worship Him alone (Surah Adh-Dhariyat: 56).","car":"خلقنا الله ليعبد وحده (سورة الذاريات: ٥٦).","ben":"<p>Have you ever wondered why you are here?</p>\n<h3>The Answer is in the Quran</h3>\n<p>Allah says in the Quran: <em>&#8220;And I did not create the jinn and mankind except to worship Me.&#8221;</em> (Surah Adh-Dhariyat: 56)</p>\n<h3>What Does Worship Mean?</h3>\n<p>Worship means loving Allah, obeying Him, praying to Him, and being good to others &#8212; all for Allah alone.</p>\n<h3>This is Our Purpose</h3>\n<p>We were created for a beautiful purpose &#8212; to know Allah, love Him, and worship Him.</p>\n<div class='lesson-highlight'>Remember: You were created to worship Allah alone!</div>","bar":"<p>هل تساءلت يوماً لماذا أنت هنا?</p>\n<h3>الجواب في القرآن</h3>\n<p>يقول الله في القرآن: <em>وما خلقت الجن والإنس إلا ليعبدون</em> (سورة الذاريات: ٥٦)</p>\n<h3>ماذا يعني العبادة؟</h3>\n<p>العبادة تعني حب الله وطاعته وصلاته والإحسان إلى الآخرين &#8212; كل ذلك لله وحده.</p>\n<h3>هذه هي رسالتنا</h3>\n<p>خلقنا الله لغرض جميل &#8212; أن نعرف الله ونحبه ونعبده.</p>\n<div class='lesson-highlight'>تذكّر: خُلقت لتعبد الله وحده!</div>","prev":"tawheed-1-5","next":"tawheed-2-2"},
    {"file":"tawheed-2-2","unit":2,"num":2,"ten":"The Word of Tawheed","tar":"كلمة التوحيد","cen":"La ilaha illa Allah &#8212; There is no one worthy of worship in truth except Allah.","car":"لا إله إلا الله &#8212; لا معبود بحق إلا الله.","ben":"<p>The most important sentence a Muslim can say!</p>\n<h3>What Does It Mean?</h3>\n<p><strong>La ilaha illa Allah</strong> means: &#8220;There is no god but Allah.&#8221;</p>\n<p>It means that only Allah deserves to be worshipped. No one else &#8212; not a statue, not a person, not anything.</p>\n<h3>Why is it Important?</h3>\n<p>This sentence is the key to Islam. When you say it truly from your heart, you become a Muslim!</p>\n<h3>Say it Every Day</h3>\n<p>Try to say <strong>La ilaha illa Allah</strong> every day. It will make your heart full of light.</p>\n<div class='lesson-highlight'>La ilaha illa Allah &#8212; The most beautiful words in the world!</div>","bar":"<p>أجمل جملة يمكن أن يقولها المسلم!</p>\n<h3>ماذا تعني؟</h3>\n<p><strong>لا إله إلا الله</strong> تعني: لا معبود بحق إلا الله.</p>\n<p>تعني أن الله وحده هو المستحق للعبادة. لا أحد غيره &#8212; لا تمثال، ولا شخص، ولا شيء.</p>\n<h3>لماذا هي مهمة؟</h3>\n<p>هذه الجملة هي مفتاح الإسلام. عندما تقولها بصدق من قلبك، تصبح مسلماً!</p>\n<h3>قلها كل يوم</h3>\n<p>حاول أن تقول لا إله إلا الله كل يوم. ستملأ قلبك بالنور.</p>\n<div class='lesson-highlight'>لا إله إلا الله &#8212; أجمل كلمات في العالم!</div>","prev":"tawheed-2-1","next":"tawheed-2-3"},
    {"file":"tawheed-2-3","unit":2,"num":3,"ten":"I Am a Muslim","tar":"أنا مسلم","cen":"I obey Allah my Lord, pray, fast, and call upon Him alone.","car":"أطيع الله ربي، وأصلي، وأصوم، وأدعوه وحده.","ben":"<p>Being a Muslim is a wonderful blessing!</p>\n<h3>I Obey Allah</h3>\n<p>As a Muslim, I try to do what Allah wants me to do and stay away from what He forbids.</p>\n<h3>I Pray</h3>\n<p>I pray five times a day to talk to Allah. It makes my heart happy and close to Him.</p>\n<h3>I Fast</h3>\n<p>During Ramadan, I fast to learn patience and to get closer to Allah.</p>\n<h3>I Call Upon Allah Alone</h3>\n<p>When I need something, I ask Allah &#8212; not anyone else. He is the One who can help me.</p>\n<div class='lesson-highlight'>Being a Muslim is the best gift ever! Alhamdulillah!</div>","bar":"<p>أن تكون مسلماً نعمة عظيمة!</p>\n<h3>أطيع الله</h3>\n<p>كمسلم، أحاول أن أفعل ما يريد الله مني وأتجنب ما حرمته.</p>\n<h3>أصلي</h3>\n<p>أصلي خمس مرات في اليوم لأتحدث مع الله. يملأ قلبي السعادة وقربي منه.</p>\n<h3>أصوم</h3>\n<p>في رمضان أصوم لأتعلّم الصبر وأقترب من الله.</p>\n<h3>أدعو الله وحده</h3>\n<p>عندما أحتاج شيئاً، أسأل الله &#8212; لا أحد غيره. هو الذي يمكنه مساعدتي.</p>\n<div class='lesson-highlight'>أن تكون مسلماً أفضل هدية على الإطلاق! الحمد لله!</div>","prev":"tawheed-2-2","next":"tawheed-2-4"},
    {"file":"tawheed-2-4","unit":2,"num":4,"ten":"I Love Allah My Lord","tar":"أحب الله ربي","cen":"I worship Allah alone without partners and love Him for making me a Muslim.","car":"أعبد الله وحده دون شركاء وأحبه لأنني مسلم.","ben":"<p>Loving Allah is the most beautiful feeling!</p>\n<h3>Why I Love Allah</h3>\n<p>Allah created me, gives me food and water, and takes care of me every single day. How can I not love Him?</p>\n<h3>How Do I Show My Love?</h3>\n<p>I show my love by praying, being kind, saying thank you (Alhamdulillah), and being honest.</p>\n<h3>Allah Loves Me Too</h3>\n<p>When we love Allah and try our best to obey Him, Allah loves us even more!</p>\n<div class='lesson-highlight'>Say with your heart: I love Allah, my Lord!</div>","bar":"<p>حب الله أجمل شعور!</p>\n<h3>لماذا أحب الله</h3>\n<p>الله خلقني وأطعمني وسقاني ويرعاني كل يوم. كيف لا أحبه?</p>\n<h3>كيف أُظهر حبي؟</h3>\n<p>أُظهر حبي بالصلاة وباللطف وبالشكر (الحمد لله) وبالصدق.</p>\n<h3>الله يحبني أيضاً</h3>\n<p>عندما نحب الله ونحاول طاعته، يحبنا الله أكثر!</p>\n<div class='lesson-highlight'>قل بقلبك: أحب الله ربي!</div>","prev":"tawheed-2-3","next":"tawheed-3-1"},
    {"file":"tawheed-3-1","unit":3,"num":1,"ten":"My Religion is Islam","tar":"ديني الإسلام","cen":"Islam is the true religion (Surah Ali 'Imran: 19).","car":"الإسلام هو الدين الحق (سورة آل عمران: ١٩).","ben":"<p>Allah chose Islam for us &#8212; and it is the best religion!</p>\n<h3>What is Islam?</h3>\n<p>Islam means submitting to Allah and obeying Him. It is a beautiful way of life.</p>\n<h3>Allah Says Islam is the Truth</h3>\n<p>In the Quran, Allah says: <em>&#8220;Indeed, the religion in the sight of Allah is Islam.&#8221;</em> (Ali &#8217;Imran: 19)</p>\n<h3>I Am Proud to Be Muslim</h3>\n<p>Being Muslim is not just a name &#8212; it is a way of living with kindness, honesty, and love for Allah.</p>\n<div class='lesson-highlight'>My religion is Islam &#8212; the best religion in the world!</div>","bar":"<p>اختار الله الإسلام لنا &#8212; وهو أفضل دين!</p>\n<h3>ما هو الإسلام؟</h3>\n<p>الإسلام يعني الاستسلام لله وطاعته. طريقة حياة جميلة.</p>\n<h3>يقول الله إن الإسلام هو الحق</h3>\n<p>في القرآن يقول الله: <em>إن الدين عند الله الإسلام</em> (آل عمران: ١٩)</p>\n<h3>أنا فخور بأنني مسلم</h3>\n<p>المسلم ليس مجرد اسم &#8212; بل هو طريقة حياة باللطف والصدق وحب الله.</p>\n<div class='lesson-highlight'>ديني الإسلام &#8212; أفضل دين في العالم!</div>","prev":"tawheed-2-4","next":"tawheed-3-2"},
    {"file":"tawheed-3-2","unit":3,"num":2,"ten":"The Two Testimonies","tar":"الشهادتان","cen":"Learning the Shahada: La ilaha illa Allah, Muhammadun Rasoolullah.","car":"تعلّم الشهادتين: لا إله إلا الله، محمّد رسول الله.","ben":"<p>The Shahada is the most important statement in Islam!</p>\n<h3>The First Testimony</h3>\n<p><strong>La ilaha illa Allah</strong> &#8212; There is no god but Allah.</p>\n<p>This means: I believe that only Allah deserves to be worshipped.</p>\n<h3>The Second Testimony</h3>\n<p><strong>Muhammadun Rasoolullah</strong> &#8212; Muhammad is the Messenger of Allah.</p>\n<p>This means: I believe in Prophet Muhammad (\ufe9f) and follow his teachings.</p>\n<h3>Say It from Your Heart</h3>\n<p>The Shahada is not just words &#8212; it comes from deep inside your heart.</p>\n<div class='lesson-highlight'>La ilaha illa Allah, Muhammadun Rasoolullah!</div>","bar":"<p>الشهادتان أهم عبارة في الإسلام!</p>\n<h3>الشهادة الأولى</h3>\n<p><strong>لا إله إلا الله</strong> &#8212; لا معبود بحق إلا الله.</p>\n<p>هذا يعني: أؤمن أن الله وحده المستحق للعبادة.</p>\n<h3>الشهادة الثانية</h3>\n<p><strong>محمّد رسول الله</strong> &#8212; محمّد رسول الله.</p>\n<p>هذا يعني: أؤمن بالنبي محمّد (\ufe9f) وأتبع تعليمه.</p>\n<h3>قلها من قلبك</h3>\n<p>الشهادتان ليست مجرد كلام &#8212; تأتي من أعماق قلبك.</p>\n<div class='lesson-highlight'>لا إله إلا الله، محمّد رسول الله!</div>","prev":"tawheed-3-1","next":"tawheed-3-3"},
    {"file":"tawheed-3-3","unit":3,"num":3,"ten":"Love for the Prophet (\ufe9f)","tar":"حب النبي (\ufe9f)","cen":"Loving Prophet Muhammad (\ufe9f), the best of mankind.","car":"حب النبي محمّد (\ufe9f)، خير الناس.","ben":"<p>We love Prophet Muhammad (\ufe9f) more than anyone!</p>\n<h3>Who Was the Prophet?</h3>\n<p>Prophet Muhammad (\ufe9f) was born in Makkah. He was the kindest, bravest, and most honest person.</p>\n<h3>He Taught Us Everything</h3>\n<p>The Prophet (\ufe9f) taught us how to pray, how to be kind to our parents, how to share with others, and how to love Allah.</p>\n<h3>How to Show Love for the Prophet</h3>\n<p>We show our love by following his Sunnah &#8212; saying Salam, praying on time, eating with our right hand, and being kind.</p>\n<div class='lesson-highlight'>Say &#8220;Sallallahu Alaihi Wasallam&#8221; every time you hear the Prophet&#8217;s name!</div>","bar":"<p>نحب النبي محمّد (\ufe9f) أكثر من أي شخص!</p>\n<h3>من كان النبي؟</h3>\n<p>وُلد النبي محمّد (\ufe9f) في مكة. كان أكرم الناس وأشجعهم وأصدقهم.</p>\n<h3>علّمنا كل شيء</h3>\n<p>علّمنا النبي (\ufe9f) كيف نصلي وكيف نكون طيبين مع آبائنا وكيف نشارك الآخرين وكيف نحب الله.</p>\n<h3>كيف نُظهر حب النبي</h3>\n<p>نُظهر حبنا باتباع سنته &#8212; قول السلام والصلاة في وقتها والأكل باليد اليمنى واللطف.</p>\n<div class='lesson-highlight'>قل &#8220;صلى الله عليه وسلم&#8221; كل مرة تسمع فيها اسم النبي!</div>","prev":"tawheed-3-2","next":"tawheed-3-4"},
    {"file":"tawheed-3-4","unit":3,"num":4,"ten":"Love for the Companions","tar":"حب الصحابة","cen":"Loving Abu Bakr, Umar, Uthman, and Ali (radhiyallahu anhum).","car":"حب أبي بكر وعمر وعثمان وعلي (رضي الله عنهم).","ben":"<p>The Companions of the Prophet (\ufe9f) were amazing people!</p>\n<h3>Who Were the Companions?</h3>\n<p>The Companions (Sahabah) were the people who followed Prophet Muhammad (\ufe9f) and learned from him directly.</p>\n<h3>The Four Great Companions</h3>\n<p><strong>Abu Bakr</strong> (radhiyallahu anhu) &#8212; The Prophet&#8217;s best friend, very kind and generous.</p>\n<p><strong>Umar</strong> (radhiyallahu anhu) &#8212; Very strong and fair, he loved justice.</p>\n<p><strong>Uthman</strong> (radhiyallahu anhu) &#8212; Very generous, he bought water for everyone.</p>\n<p><strong>Ali</strong> (radhiyallahu anhu) &#8212; Very brave and wise, even as a young boy.</p>\n<h3>We Love Them All</h3>\n<p>We love all the Companions because they helped spread Islam and were the best generation.</p>\n<div class='lesson-highlight'>Say &#8220;Radhi Allahu Anhum&#8221; &#8212; May Allah be pleased with them!</div>","bar":"<p>أصحاب النبي (\ufe9f) كانوا أشخاصاً رائعين!</p>\n<h3>من هم الصحابة؟</h3>\n<p>الصحاباء هم الناس الذين تبعوا النبي محمّد (\ufe9f) وتعلّموا منه مباشرة.</p>\n<h3>الأربعة الكبار</h3>\n<p><strong>أبو بكر</strong> (رضي الله عنه) &#8212; صديق النبي، كريم وطيب جداً.</p>\n<p><strong>عمر</strong> (رضي الله عنه) &#8212; قوي وعادل، أحب العدالة.</p>\n<p><strong>عثمان</strong> (رضي الله عنه) &#8212; كريم جداً، اشترى ماء للجميع.</p>\n<p><strong>علي</strong> (رضي الله عنه) &#8212; شجاع وحكيم حتى في صغره.</p>\n<h3>نحبهم جميعاً</h3>\n<p>نحب جميع الصحابة لأنهم ساعدوا في نشر الإسلام وكانوا أفضل جيل.</p>\n<div class='lesson-highlight'>قل &#8220;رضي الله عنهم&#8221; &#8212; رضي الله عنهم!</div>","prev":"tawheed-3-3","next":None},
]

template = """<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{ten} | SiratKids</title>
    <link rel="stylesheet" href="../css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Noto+Naskh+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar">
        <a href="../index.html" class="nav-logo">
            <img src="../images/logo.svg" alt="" class="nav-logo-img">
            <span class="nav-brand">SiratKids</span>
        </a>
        <div class="nav-links">
            <a href="../index.html">Home</a>
            <a href="../index.html#tawheed-curriculum">Curriculum</a>
        </div>
    </nav>

    <header class="lesson-hero">
        <div class="lesson-hero-inner">
            <p class="lesson-unit">Unit {unit}</p>
            <h1 class="lesson-title">
                <span class="en">{ten}</span>
                <span class="ar" dir="rtl">{tar}</span>
            </h1>
            <p class="lesson-concept-block">
                <span class="en">{cen}</span>
                <span class="ar" dir="rtl">{car}</span>
            </p>
        </div>
    </header>

    <main class="lesson-main">
        <div class="lesson-body en">{ben}</div>
        <div class="lesson-body ar" dir="rtl">{bar}</div>

        <div class="lesson-nav">
            {prev_link}
            <a href="../index.html#tawheed-curriculum" class="lesson-nav-index">Index</a>
            {next_link}
        </div>
    </main>

    <footer class="footer">
        <p>&copy; 2026 SiratKids. All rights reserved.</p>
    </footer>
    <script src="../js/main.js"></script>
</body>
</html>"""

for l in lessons:
    prev = '<a href="{}.html" class="lesson-nav-prev">&#8592; Previous</a>'.format(l["prev"]) if l["prev"] else "<span></span>"
    nxt = '<a href="{}.html" class="lesson-nav-next">Next &#8594;</a>'.format(l["next"]) if l["next"] else "<span></span>"

    html = template.format(
        ten=l["ten"], tar=l["tar"], unit=l["unit"],
        cen=l["cen"], car=l["car"],
        ben=l["ben"], bar=l["bar"],
        prev_link=prev, next_link=nxt
    )

    path = os.path.join("lessons", l["file"] + ".html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print("Created: " + path)

print("Done! {} lessons.".format(len(lessons)))
